/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package hibernate.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import modelo.usuario.Usuario;
import java.util.Date;

/** 
 * MyEclipse Struts
 * Creation date: 01-07-2010
 * 
 * XDoclet definition:
 * @struts.form name="editarUsuarioForm"
 */
public class EditarUsuarioForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private Usuario usuario=new Usuario();
	private Boolean confirm=new Boolean(false);
	
	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Date getFecAcceso(){
		return usuario.getFecAcceso();
	}
	
	public String getIdUsuario(){
		return usuario.getIdUsuario();
	}
	
	public String getPassword(){
		return usuario.getPassword();
	}
	
	public String getApellidos(){
		return usuario.getApellidos();
	}
	
	public String getEmail(){
		return usuario.getEmail();
	}
	
	public String getNombre(){
		return usuario.getNombre();
	}
	
	public String getTelefono(){
		return usuario.getTelefono();
	}
	
	public String getTipo(){
		return usuario.getTipo();
	}
	
	public void setFecAcceso(Date fecAcceso){
		usuario.setFecAcceso(fecAcceso);
	}
	
	public void setIdUsuario(String idUsuario){
		usuario.setIdUsuario(idUsuario);
	}
	
	public void setPassword(String password){
		usuario.setPassword(password);
	}
	
	public void setApellidos(String apellidos){
		usuario.setApellidos(apellidos);
	}
	
	public void setEmail(String email){
		 usuario.setEmail(email);
	}
	
	public void setNombre(String nombre){
		 usuario.setNombre(nombre);
	}
	
	public void setTelefono(String telefono){
		 usuario.setTelefono(telefono);
	}
	
	public void setTipo(String tipo){
		 usuario.setTipo(tipo);
	}
	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	public Boolean getConfirm() {
		return confirm;
	}

	public void setConfirm(Boolean confirm) {
		this.confirm = confirm;
	}
}