/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package hibernate.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import modelo.pelicula.Pelicula;
import modelo.reparto.Reparto;

/** 
 * MyEclipse Struts
 * Creation date: 01-08-2010
 * 
 * XDoclet definition:
 * @struts.form name="editarPeliculaForm"
 */
public class EditarPeliculaForm extends ActionForm {
	
	private Pelicula pelicula=new Pelicula();
	private Reparto[] reparto=new Reparto[0];
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
	
	public Reparto[] getReparto(){
		return reparto;
	}
	
	public void setReparto(Reparto[] reparto){
		this.reparto=reparto;
	}

	public Pelicula getPelicula() {
		return pelicula;
	}

	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}
	
	public String getApellidosDirector() {
		return pelicula.getApellidosDirector();
	}

	public void setApellidosDirector(String apellidosDirector) {
		this.pelicula.setApellidosDirector(apellidosDirector);
	}

	public String getNombreDirector() {
		return pelicula.getNombreDirector();
	}

	public void setNombreDirector(String nombreDirector) {
		this.pelicula.setNombreDirector(nombreDirector);
	}

	public String getIdioma() {
		return pelicula.getIdioma();
	}

	public void setIdioma(String idioma) {
		this.pelicula.setIdioma(idioma);
	}

	public String getPathImagen() {
		return pelicula.getPathImagen();
	}

	public void setPathImagen(String pathImagen) {
		this.pelicula.setPathImagen(pathImagen);
	}

	public String getTitulo() {
		return pelicula.getTitulo();
	}

	public void setTitulo(String titulo) {
		this.pelicula.setTitulo(titulo);
	}

	public Double getCoste() {
		return pelicula.getCoste();
	}

	public void setCoste(Double coste) {
		this.pelicula.setCoste(coste);
	}

	public Double getPrecio() {
		return pelicula.getPrecio();
	}

	public void setPrecio(Double precio) {
		this.pelicula.setPrecio(precio);
	}

	public Integer getDisponibilidad() {
		return pelicula.getDisponibilidad();
	}

	public void setDisponibilidad(Integer disponibilidad) {
		this.pelicula.setDisponibilidad(disponibilidad);
	}
	
	public String getAnyo(){
		return pelicula.getAnyo();
	}
	
	public void setAnyo(String anyo){
		pelicula.setAnyo(anyo);
	}
	
	public String getSinopsis(){
		return pelicula.getSinopsis();
	}
	
	public void setSinopsis(String sinopsis){
		pelicula.setSinopsis(sinopsis);
	}
}