/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package hibernate.struts.form;

import javax.servlet.http.HttpServletRequest;

import modelo.pelicula.Pelicula;
import modelo.usuario.Usuario;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-08-2010
 * 
 * XDoclet definition:
 * @struts.form name="listaPeliculasForm"
 */
public class ListaPeliculasForm extends ActionForm {

	private Pelicula[] peliculas=new Pelicula[0];
	/*
	 * Generated Methods
	 */

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
		peliculas=new Pelicula[0];
	}

	public Pelicula[] getPeliculas() {
		return peliculas;
	}

	public void setPeliculas(Pelicula[] listpeliculas) {
		this.peliculas = listpeliculas;
	}
}