/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package hibernate.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

import modelo.compra.*;

/** 
 * MyEclipse Struts
 * Creation date: 01-09-2010
 * 
 * XDoclet definition:
 * @struts.form name="listaComprasForm"
 */
public class ListaComprasForm extends ActionForm {
	
	private Compra[] compra=new Compra[0];
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}


	
	public Compra[] getCompra() {
		return compra;
	}

	public void setCompra(Compra[] compra) {
		this.compra = compra;
	}
//
//	public String getDireccion(){
//		return compra.getDireccion();
//	}
//	public void setDireccion(String direccion){
//		compra.setDireccion(direccion);
//	}
//	public String getFormaPago(){
//		return compra.getFormaPago();
//	}
//	public void setFormaPago(String formapago){
//		compra.setFormaPago(formapago);
//	}
//	public CompraId getCompraId(){
//		return compra.getId();
//	}
//	public void setCompraId(CompraId id){
//		compra.setId(id);
//	}
//	public String getNumTarjeta(){
//		return compra.getNumTarjeta();
//	}
//	public void setNumTarjeta(String numtarjeta){
//		compra.setNumTarjeta(numtarjeta);
//	}
//	
	
}