/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package hibernate.struts.action;

import hibernate.struts.form.EditarUsuarioForm;

import org.apache.struts.actions.DispatchAction;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
//import org.apache.struts.action.Action;
import controlador.TestModelo;
import java.util.Date;
/** 
 * MyEclipse Struts
 * Creation date: 01-07-2010
 * 
 * XDoclet definition:
 * @struts.action path="/editarUsuario" name="editarUsuarioForm" parameter="do" scope="request" validate="true"
 * @struts.action-forward name="eliminarUsuario" path="/jsp/eliminarUsuario.jsp"
 * @struts.action-forward name="modificarUsuario" path="/jsp/modificarUsuario.jsp"
 * @struts.action-forward name="nuevoUsuario" path="/jsp/nuevoUsuario.jsp"
 */
public class EditarUsuarioAction extends DispatchAction {
	
	
	public ActionForward eliminarUsuario(
			             ActionMapping mapping,
			             ActionForm form,
			             HttpServletRequest request,
			             HttpServletResponse response){
		System.out.print("eliminar usuario: ");
		EditarUsuarioForm editarUsuarioForm=(EditarUsuarioForm)form;
		TestModelo admin=new TestModelo();
		editarUsuarioForm.setUsuario(admin.getUsuario(request.getParameter("idUsuario")));
		return mapping.findForward("eliminarUsuario");
	}
	
	public ActionForward elimUsuarioConf(
            ActionMapping mapping,
            ActionForm form,
            HttpServletRequest request,
            HttpServletResponse response){
		TestModelo admin=new TestModelo();
		admin.eliminarUsuario(request.getParameter("idUsuario"));
		System.out.println("Eliminado el usuario");
		return mapping.findForward("elimUsuarioConf");
	}
	
	public ActionForward verUsuario(
            ActionMapping mapping,
            ActionForm form,
            HttpServletRequest request,
            HttpServletResponse response){
		EditarUsuarioForm editarUsuarioForm=(EditarUsuarioForm)form;
		TestModelo admin=new TestModelo();
		System.out.println("Se ha solicitado ver detalle de usuario");
		editarUsuarioForm.setUsuario(admin.getUsuario(request.getParameter("idUsuario")));
		return mapping.findForward("verUsuario");
	}
	
	public ActionForward nuevoUsuario(
            ActionMapping mapping,
            ActionForm form,
            HttpServletRequest request,
            HttpServletResponse response){
		return mapping.findForward("nuevoUsuario");
	}
	
	public ActionForward nuevoUsuarioSave(
            ActionMapping mapping,
            ActionForm form,
            HttpServletRequest request,
            HttpServletResponse response){
		String idUsuario=request.getParameter("idUsuario");
		String password=request.getParameter("password");
		String email=request.getParameter("email");
		String tipo=request.getParameter("tipo");
		String nombre=request.getParameter("nombre");
		String apellidos=request.getParameter("apellidos");
		String telefono=request.getParameter("telefono");
		System.out.println(idUsuario+" "+password);
		Date fecAcceso=new Date();
		TestModelo admin=new TestModelo();
		admin.crearUsuario(idUsuario.trim(),  password,  email,
				 tipo,  nombre,  apellidos,  telefono,
					fecAcceso);
		System.out.println("El usuario se ha creado");
		return mapping.findForward("nuevoUsuarioSave");
	}
}