/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package hibernate.struts.action;

import hibernate.struts.form.ListaUsuariosForm;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import controlador.TestModelo;
/** 
 * MyEclipse Struts
 * Creation date: 01-07-2010
 * 
 * XDoclet definition:
 * @struts.action path="/listaUsuarios" name="listaUsuariosForm" input="/jsp/listaUsuarios.jsp" scope="request" validate="true"
 */
public class ListaUsuariosAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ListaUsuariosForm listaUsuariosForm = (ListaUsuariosForm) form;// TODO Auto-generated method stub
		TestModelo admin=new TestModelo();
		listaUsuariosForm.setUsuarios(admin.listarUsuarios());
		return mapping.findForward("showlist");
		
	}
}