/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package hibernate.struts.action;

import hibernate.struts.form.ListaComprasForm;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import controlador.TestModelo;

/** 
 * MyEclipse Struts
 * Creation date: 01-09-2010
 * 
 * XDoclet definition:
 * @struts.action path="/listaCompras" name="listaComprasForm" input="/jsp/listaCompras.jsp" scope="request" validate="true"
 */
public class ListaComprasAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ListaComprasForm listaComprasForm = (ListaComprasForm) form;// TODO Auto-generated method stub
		TestModelo admin=new TestModelo();
		listaComprasForm.setCompra(admin.listarCompras());
		return mapping.findForward("showlist");
	}
}